version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: direct
    groups:
      python-dependencies:
        patterns: ["*"]
        update-types: [minor, patch]
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    allow:
      - dependency-type: direct
    commit-message:
      prefix: build
      include: scope
