[virtualenvs]
in-project = true
# This setting is useful if you're using pyenv to test with multiple versions
# of python. If so, uncomment this to create a virtual environment based on the
# currently active python version.

# prefer-active-python = true
